server:
  port: 10002


spring:
  application:
    name: eureka-feign-upload-client

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: eureka-feign-upload-client  #服务名称变更
    prefer-ip-address: true     #访问路径可以显示IP地址
