server:
  port: 1112


spring:
  application:
    name: one-quartz

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver      #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud_learn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    password: 123456


